services:
  db_cdci:
    image: postgres
    container_name: db_cdci
    restart: always
    ports:
      - 4455:5432
    env_file:
      - .env.test
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_cdci
    env_file:
      - .env.test

volumes:
  postgres:
